name: $(major).$(minor).$(revision)$(Rev:.r)
trigger:
- main

variables:
  agentSolution: 'All.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: 5
  minor: 0
  revision: 0
  fileVersion: '$(Build.BuildNumber)'

jobs:
- job: build
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadSecureFile@1
    displayName: 'Download Signing Key'  
    name: loupeAgentSigningKey
    inputs:
      secureFile: 'loupe.agent.snk'
      overWrite: true

  - task: DownloadSecureFile@1
    displayName: 'Download Code Signing Cert'  
    name: GibraltarSoftwareCCC
    inputs:
      secureFile: 'GibraltarSoftwareCCC.pfx'
      overWrite: true

  - task: CopyFiles@2
    displayName: 'Copy Signing Key to Build Location'  
    inputs:
      SourceFolder: '$(Agent.TempDirectory)'
      Contents: 'loupe.agent.snk'
      TargetFolder: '$(Build.SourcesDirectory)'

  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(agentSolution)'

  - task: VSBuild@1
    inputs:
      solution: '$(agentSolution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'
      msbuildArgs: '/p:CustomVersion=$(fileVersion) /p:CustomInformationalVersion=$(fileVersion) /p:PackageVersion=$(fileVersion)'

  - task: CopyFiles@2
    displayName: 'Stage NuGet Packages'  
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)\src'
      contents: '**\bin\**\?(*.nupkg|*.snupkg)'
      flattenFolders: true
      targetFolder: '$(Build.ArtifactStagingDirectory)\packages'

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.nupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword f4rd+GM% -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: NuGetCommand@2
    displayName: 'Sign NuGet Symbol Packages'  
    inputs:
      command: 'custom'
      arguments: sign $(Build.ArtifactStagingDirectory)\packages\*.snupkg -CertificatePath $(Agent.TempDirectory)/GibraltarSoftwareCCC.pfx -CertificatePassword f4rd+GM% -Timestamper http://timestamp.comodoca.com -Verbosity detailed

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)/packages'
      artifactName: packages